version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: PizzaSite
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  webapi:
    build:
      context: ./backend/PizzaService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnection: "Host=db;Database=PizzaSite;Username=postgres;Password=12345"
      StoredPizzaImagesPath: "wwwroot/images"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - webapi-data:/app/wwwroot
    networks:
      - backend

  frontend:
    build:
      context: ./frontend/pizza-site
      dockerfile: Dockerfile
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8080"
    depends_on:
      - db
      - webapi
    ports:
      - "3000:3000"
    networks:
      - backend

volumes:
  pgdata:
  webapi-data:

networks:
  backend:

